[IT-3697] Make sure the SSM agent is installed
Sage-Bionetworks-IT/packer-amazonlinux-docker pull request #14
Opened 2024-06-12 17:57 UTC by jesusaurus

The SSM agent is no longer installed by default on the base AMI, install it with packer. Also give `ssm-user` access to run docker.

2024-06-13 22:00 UTC, zaro0508 requested changes
> The SSM agent is no longer installed by default on the base AMI

according to the AWS docs, the SSM agent is pre-installed https://docs.aws.amazon.com/systems-manager/latest/userguide/ami-preinstalled-agent.html

could it be that we might not be building on top of the correct AWS base AMI?  or that the service catalog product is not using the correct AMI?

2024-06-20 23:11 UTC, jesusaurus commented
@zaro0508 oh, thanks, we _were_ building off of two different amazon base image types, depending on which was most recently updated. The working images were based off of the AWS ECS-optimized image, and the one that didn't have an ssm agent installed was based off of the minimal AWS image.

2024-06-24 18:12 UTC, zaro0508 requested changes
the purpose of this PR has completely changed.  can you please update the PR subject and description to reflect what you are doing in this PR?

2024-07-01 23:32 UTC, zaro0508 approved these changes

2024-07-02 16:28 UTC, merged